# Generated by Django 3.1.7 on 2021-04-06 00:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_longitudes', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('p_latitudes', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('driver_long', models.FloatField(null=True)),
                ('driver_lat', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('volume', models.FloatField()),
                ('receiver', models.CharField(max_length=15)),
                ('destination_long', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('sender', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('estimated_time', models.DateTimeField(null=True)),
                ('truck_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_truck', to='core.route')),
            ],
        ),
    ]
