# Generated by Django 3.1.7 on 2021-04-02 06:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('truck_id', models.IntegerField()),
                ('volume', models.FloatField()),
                ('receiver', models.CharField(max_length=15)),
                ('des_latitude', models.FloatField()),
                ('des_longitude', models.FloatField()),
                ('sender', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('estimated_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_longitudes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('p_latitudes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
