# Generated by Django 3.1.7 on 2021-04-03 14:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210402_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='des_latitude',
        ),
        migrations.RemoveField(
            model_name='package',
            name='des_longitude',
        ),
        migrations.AlterField(
            model_name='route',
            name='p_latitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='route',
            name='p_longitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coordinates'),
        ),
        migrations.AddField(
            model_name='route',
            name='driver_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coordinates'),
        ),
    ]
