# Generated by Django 3.1.7 on 2021-04-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210403_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='driver_location',
        ),
        migrations.AddField(
            model_name='package',
            name='destination_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='destination_long',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='driver_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='driver_long',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
